In [1]:
import pandas as pd
import numpy as np
import scipy
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from sklearn.model_selection import train_test_split 
from sklearn.metrics import r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
pd.set_option('display.max_columns',100)

In [2]:
data = pd.read_csv('XYZCorp_LendingData.csv',parse_dates=['issue_d'])

/usr/local/Cellar/ipython/7.7.0/libexec/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (17,45,53) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.head(3)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,default_ind
0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,n,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0,Jan-85,1,NaN,NaN,3,0,13648,83.7,9,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.0,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,n,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0,Apr-99,5,NaN,NaN,3,0,1687,9.4,4,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.0,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,n,NaN,small_business,real estate business,606xx,IL,8.72,0,Nov-01,2,NaN,NaN,2,0,2956,98.5,10,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.0,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [4]:
nulls = dict(data.isnull().sum()/len(data)*100)
drops = []
for i in nulls:
    if nulls[i] > 65:
        drops.append(i)
drops

['desc',
 'mths_since_last_record',
 'mths_since_last_major_derog',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'open_acc_6m',
 'open_il_6m',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m']

In [5]:
data = data.drop(columns=drops)
data.isnull().sum()/len(data)*100

id                             0.000000
member_id                      0.000000
loan_amnt                      0.000000
funded_amnt                    0.000000
funded_amnt_inv                0.000000
term                           0.000000
int_rate                       0.000000
installment                    0.000000
grade                          0.000000
sub_grade                      0.000000
emp_title                      5.776261
emp_length                     5.030673
home_ownership                 0.000000
annual_inc                     0.000000
verification_status            0.000000
issue_d                        0.000000
pymnt_plan                     0.000000
purpose                        0.000000
title                          0.003855
zip_code                       0.000000
addr_state                     0.000000
dti                            0.000000
delinq_2yrs                    0.000000
earliest_cr_line               0.000000
inq_last_6mths                 0.000000
mths_since_last_delinq        51.381767
open_acc                       0.000000
pub_rec                        0.000000
revol_bal                      0.000000
revol_util                     0.052105
total_acc                      0.000000
initial_list_status            0.000000
out_prncp                      0.000000
out_prncp_inv                  0.000000
total_pymnt                    0.000000
total_pymnt_inv                0.000000
total_rec_prncp                0.000000
total_rec_int                  0.000000
total_rec_late_fee             0.000000
recoveries                     0.000000
collection_recovery_fee        0.000000
last_pymnt_d                   1.035318
last_pymnt_amnt                0.000000
next_pymnt_d                  29.553757
last_credit_pull_d             0.005841
collections_12_mths_ex_med     0.006542
policy_code                    0.000000
application_type               0.000000
acc_now_delinq                 0.000000
tot_coll_amt                   7.863953
tot_cur_bal                    7.863953
total_rev_hi_lim               7.863953
default_ind                    0.000000
dtype: float64

In [6]:
data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default_ind
0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,n,credit_card,Computer,860xx,AZ,27.65,0,Jan-85,1,NaN,3,0,13648,83.7,9,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,1,INDIVIDUAL,0,NaN,NaN,NaN,0
1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,n,car,bike,309xx,GA,1.00,0,Apr-99,5,NaN,3,0,1687,9.4,4,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,1,INDIVIDUAL,0,NaN,NaN,NaN,1
2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,n,small_business,real estate business,606xx,IL,8.72,0,Nov-01,2,NaN,2,0,2956,98.5,10,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,1,INDIVIDUAL,0,NaN,NaN,NaN,0
3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,n,other,personel,917xx,CA,20.00,0,Feb-96,1,35.0,10,0,5598,21.0,37,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,1,INDIVIDUAL,0,NaN,NaN,NaN,0
4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,n,other,Personal,972xx,OR,17.94,0,Jan-96,0,38.0,15,0,27783,53.9,38,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,1,INDIVIDUAL,0,NaN,NaN,NaN,0

In [7]:
data.emp_title = data.emp_title.fillna('Not Collected')
data.emp_length = data.emp_length.fillna('0')
data.mths_since_last_delinq = data.mths_since_last_delinq.fillna('0')
data.revol_util = data.revol_util.fillna('0')
data.next_pymnt_d = data.next_pymnt_d.fillna('Not Collected')
data.last_pymnt_d = data.last_pymnt_d.fillna('Not Collected')
data.last_credit_pull_d = data.last_credit_pull_d.fillna('Not Collected')

In [8]:
data = data[data.tot_cur_bal.notnull()]
data.isnull().sum()

id                             0
member_id                      0
loan_amnt                      0
funded_amnt                    0
funded_amnt_inv                0
term                           0
int_rate                       0
installment                    0
grade                          0
sub_grade                      0
emp_title                      0
emp_length                     0
home_ownership                 0
annual_inc                     0
verification_status            0
issue_d                        0
pymnt_plan                     0
purpose                        0
title                         22
zip_code                       0
addr_state                     0
dti                            0
delinq_2yrs                    0
earliest_cr_line               0
inq_last_6mths                 0
mths_since_last_delinq         0
open_acc                       0
pub_rec                        0
revol_bal                      0
revol_util                     0
total_acc                      0
initial_list_status            0
out_prncp                      0
out_prncp_inv                  0
total_pymnt                    0
total_pymnt_inv                0
total_rec_prncp                0
total_rec_int                  0
total_rec_late_fee             0
recoveries                     0
collection_recovery_fee        0
last_pymnt_d                   0
last_pymnt_amnt                0
next_pymnt_d                   0
last_credit_pull_d             0
collections_12_mths_ex_med     0
policy_code                    0
application_type               0
acc_now_delinq                 0
tot_coll_amt                   0
tot_cur_bal                    0
total_rev_hi_lim               0
default_ind                    0
dtype: int64

In [9]:
data = data.drop(columns=['last_pymnt_d','last_pymnt_amnt','last_credit_pull_d','next_pymnt_d','mths_since_last_delinq'])

In [10]:
data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,default_ind
39694,10149342,12000897,27050,27050,27050.0,36 months,10.99,885.46,B,B2,Team Leadern Customer Ops & Systems,10+ years,OWN,55000.0,Verified,Dec-13,n,debt_consolidation,Debt Consolidation,481xx,MI,22.87,0,Oct-86,0,14,0,36638,61.2,27,w,10018.90,10018.90,21251.04,21251.04,17031.10,4219.94,0.0,0.0,0.0,0.0,1,INDIVIDUAL,0,0.0,114834.0,59900.0,0
39695,10159584,12011200,9750,9750,9750.0,36 months,13.98,333.14,C,C1,Medical Assistant,1 year,RENT,26000.0,Not Verified,Dec-13,n,debt_consolidation,Debt Consilation,927xx,CA,25.12,0,Jan-07,0,12,0,7967,52.8,28,f,3710.96,3710.96,7994.83,7994.83,6039.04,1955.79,0.0,0.0,0.0,0.0,1,INDIVIDUAL,0,0.0,14123.0,15100.0,0
39696,10159498,1319523,12000,12000,12000.0,36 months,6.62,368.45,A,A2,MANAGER INFORMATION DELIVERY,10+ years,MORTGAGE,105000.0,Not Verified,Dec-13,n,debt_consolidation,UNIVERSAL CARD,060xx,CT,14.05,0,Mar-94,1,12,0,13168,21.6,22,w,4266.62,4266.62,8842.80,8842.80,7733.38,1109.42,0.0,0.0,0.0,0.0,1,INDIVIDUAL,0,0.0,267646.0,61100.0,0
39697,10139658,11991209,12000,12000,12000.0,36 months,13.53,407.40,B,B5,On road manager,10+ years,RENT,40000.0,Source Verified,Dec-13,n,debt_consolidation,Debt consolidation,871xx,NM,16.94,0,Oct-98,0,7,2,5572,68.8,32,w,0.00,0.00,13359.77,13359.77,11999.99,1359.78,0.0,0.0,0.0,0.0,1,INDIVIDUAL,0,15386.0,13605.0,8100.0,0
39698,10159548,12011167,15000,15000,15000.0,36 months,8.90,476.30,A,A5,aircraft maintenance engineer,2 years,MORTGAGE,63000.0,Not Verified,Dec-13,n,debt_consolidation,Pay off,334xx,FL,16.51,0,Mar-98,0,8,0,11431,74.2,29,w,5449.27,5449.27,11431.20,11431.20,9550.73,1880.47,0.0,0.0,0.0,0.0,1,INDIVIDUAL,0,1514.0,272492.0,15400.0,0

In [11]:
data['emp_length'] = data['emp_length'].str.replace('\D*\W* years*','').str.replace('< ','')
data['emp_length'].astype('int64')

39694     10
39695      1
39696     10
39697     10
39698      2
          ..
855964     8
855965    10
855966     5
855967     1
855968    10
Name: emp_length, Length: 788656, dtype: int64

In [12]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [13]:
data.grade = data.grade.str.replace('A','0').replace('B','0').replace('C','0').replace('D','1').replace('E','1').replace('F','1').replace('G','1')

In [14]:
data.grade.unique()

array(['0', '1'], dtype=object)

In [15]:
le.fit(data['grade'])
print(list(le.classes_))
data.grade = le.transform(data['grade'])

['0', '1']

In [16]:
data.grade

39694     0
39695     0
39696     0
39697     0
39698     0
         ..
855964    0
855965    0
855966    1
855967    1
855968    0
Name: grade, Length: 788656, dtype: int64

In [17]:
le.fit(data['term'])
print(list(le.classes_))
data.term = le.transform(data['term'])

[' 36 months', ' 60 months']

In [18]:
data.term

39694     0
39695     0
39696     0
39697     0
39698     0
         ..
855964    0
855965    0
855966    1
855967    1
855968    0
Name: term, Length: 788656, dtype: int64

In [19]:
le.fit(data['sub_grade'])
print(list(le.classes_))
data.sub_grade = le.transform(data['sub_grade'])

['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3', 'G4', 'G5']

In [20]:
data.sub_grade

39694      6
39695     10
39696      1
39697      9
39698      4
          ..
855964     9
855965     9
855966    16
855967    22
855968     9
Name: sub_grade, Length: 788656, dtype: int64

In [21]:
le.fit(data['home_ownership'])
print(list(le.classes_))
data.home_ownership = le.transform(data['home_ownership'])

['ANY', 'MORTGAGE', 'NONE', 'OTHER', 'OWN', 'RENT']

In [22]:
data.home_ownership

39694     4
39695     5
39696     1
39697     5
39698     1
         ..
855964    5
855965    1
855966    5
855967    5
855968    5
Name: home_ownership, Length: 788656, dtype: int64

In [23]:
data.verification_status = data.verification_status.str.replace('Source Verified','Verified')
le.fit(data['verification_status'])
print(list(le.classes_))
data.verification_status = le.transform(data['verification_status'])

['Not Verified', 'Verified']

In [24]:
data.verification_status

39694     1
39695     0
39696     0
39697     1
39698     0
         ..
855964    1
855965    1
855966    1
855967    1
855968    1
Name: verification_status, Length: 788656, dtype: int64

In [25]:
le.fit(data['pymnt_plan'])
print(list(le.classes_))
data.pymnt_plan = le.transform(data['pymnt_plan'])

['n', 'y']

In [26]:
data.pymnt_plan

39694     0
39695     0
39696     0
39697     0
39698     0
         ..
855964    0
855965    0
855966    0
855967    0
855968    0
Name: pymnt_plan, Length: 788656, dtype: int64

In [27]:
le.fit(data['purpose'])
print(list(le.classes_))
data.purpose = le.transform(data['purpose'])

['car', 'credit_card', 'debt_consolidation', 'educational', 'home_improvement', 'house', 'major_purchase', 'medical', 'moving', 'other', 'renewable_energy', 'small_business', 'vacation', 'wedding']

In [28]:
data.purpose

39694     2
39695     2
39696     2
39697     2
39698     2
         ..
855964    2
855965    4
855966    2
855967    2
855968    1
Name: purpose, Length: 788656, dtype: int64

In [29]:
le.fit(data['application_type'])
print(list(le.classes_))
data.application_type = le.transform(data['application_type'])

['INDIVIDUAL', 'JOINT']

In [30]:
data.application_type

39694     0
39695     0
39696     0
39697     0
39698     0
         ..
855964    0
855965    0
855966    0
855967    0
855968    0
Name: application_type, Length: 788656, dtype: int64

In [31]:
le.fit(data['initial_list_status'])
print(list(le.classes_))
data.initial_list_status = le.transform(data['initial_list_status'])

['f', 'w']

In [32]:
data.initial_list_status

39694     1
39695     0
39696     1
39697     1
39698     1
         ..
855964    0
855965    0
855966    1
855967    1
855968    0
Name: initial_list_status, Length: 788656, dtype: int64

In [33]:
data = data.rename(columns={'default_ind':'approval'})

In [34]:
from datetime import datetime
data['issue_d'] = data['issue_d'].str.replace('-',' ')
data['issue_d'] = pd.to_datetime(data['issue_d'] , format ='%b %y')
data['earliest_cr_line'] = pd.to_datetime(data['earliest_cr_line'] , format ='%b-%y')
# data['issue_d'] = data['issue_d'].apply(lambda x: x.strftime('%m %y'))

In [35]:
data = data.set_index(['issue_d'])
data = data.sort_index()
data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,approval
issue_d,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2012-08-01,1476351,1734350,22400,22400,22100.0,1,14.09,522.26,0,9,Wal-Mart Stores Inc.,10,1,60000.0,1,0,2,Debt consolidation,010xx,MA,20.35,0,2000-07-01,0,16,0,17857,44.2,22,0,9272.46,9148.3,20869.150000,20589.62,13127.53,7741.62,0.0,0.00,0.0000,0.0,1,0,0,0.0,135926.0,40400.0,0
2012-08-01,1479477,1737962,12000,12000,11975.0,0,12.12,399.26,0,7,City of Atlantic city,10,5,61000.0,0,0,2,Personal,084xx,NJ,21.40,0,2006-07-01,0,13,0,12353,81.8,17,0,0.00,0.0,13584.980000,13556.68,12000.00,1584.98,0.0,0.00,0.0000,0.0,1,0,0,0.0,38192.0,15100.0,0
2012-08-01,1479621,1738125,3000,3000,3000.0,0,15.31,104.46,0,11,"mohawk valley orthopedics, pc",10,4,35000.0,0,0,2,credit card payment,120xx,NY,10.80,2,2000-11-01,3,12,0,2976,69.2,25,0,0.00,0.0,3740.506628,3740.51,3000.00,740.51,0.0,0.00,0.0000,0.0,1,0,0,0.0,8108.0,4300.0,0
2012-08-01,1479620,1738124,1200,1200,1200.0,0,12.12,39.93,0,7,Not Collected,0,5,30000.0,0,0,8,Moving,316xx,GA,14.62,0,1992-01-01,0,10,0,6490,40.6,24,0,0.00,0.0,1430.283834,1430.28,1200.00,230.28,0.0,0.00,0.0000,0.0,1,0,0,0.0,10855.0,16000.0,0
2012-08-01,1479604,1737906,16000,16000,16000.0,0,14.33,549.42,0,10,Department of social services,5,1,100000.0,0,0,2,consolidation,064xx,CT,13.08,3,1994-02-01,1,18,0,9126,58.5,36,0,0.00,0.0,10646.690000,10646.69,6700.96,2626.26,0.0,1319.47,13.0655,0.0,1,0,0,0.0,376021.0,15600.0,1

In [36]:
data.dtypes

id                                     int64
member_id                              int64
loan_amnt                              int64
funded_amnt                            int64
funded_amnt_inv                      float64
term                                   int64
int_rate                             float64
installment                          float64
grade                                  int64
sub_grade                              int64
emp_title                             object
emp_length                            object
home_ownership                         int64
annual_inc                           float64
verification_status                    int64
pymnt_plan                             int64
purpose                                int64
title                                 object
zip_code                              object
addr_state                            object
dti                                  float64
delinq_2yrs                            int64
earliest_cr_line              datetime64[ns]
inq_last_6mths                         int64
open_acc                               int64
pub_rec                                int64
revol_bal                              int64
revol_util                            object
total_acc                              int64
initial_list_status                    int64
out_prncp                            float64
out_prncp_inv                        float64
total_pymnt                          float64
total_pymnt_inv                      float64
total_rec_prncp                      float64
total_rec_int                        float64
total_rec_late_fee                   float64
recoveries                           float64
collection_recovery_fee              float64
collections_12_mths_ex_med           float64
policy_code                            int64
application_type                       int64
acc_now_delinq                         int64
tot_coll_amt                         float64
tot_cur_bal                          float64
total_rev_hi_lim                     float64
approval                               int64
dtype: object

In [37]:
data_cm = data.corr().sort_values('approval',ascending=False)
data_cm['approval']

approval                      1.000000
recoveries                    0.496454
collection_recovery_fee       0.374254
int_rate                      0.161360
total_rec_late_fee            0.130997
sub_grade                     0.127620
grade                         0.103483
inq_last_6mths                0.069652
total_rec_int                 0.043669
home_ownership                0.028528
purpose                       0.026888
term                          0.025653
verification_status           0.022265
installment                   0.013594
dti                           0.010737
loan_amnt                     0.000692
funded_amnt                   0.000686
funded_amnt_inv               0.000682
pymnt_plan                   -0.000429
acc_now_delinq               -0.000936
tot_coll_amt                 -0.001921
delinq_2yrs                  -0.004229
application_type             -0.005211
collections_12_mths_ex_med   -0.007707
open_acc                     -0.011349
total_acc                    -0.012048
pub_rec                      -0.013947
revol_bal                    -0.017852
total_pymnt                  -0.032628
total_pymnt_inv              -0.032634
annual_inc                   -0.032760
total_rev_hi_lim             -0.033620
tot_cur_bal                  -0.036335
initial_list_status          -0.075365
total_rec_prncp              -0.080986
id                           -0.209682
member_id                    -0.209784
out_prncp                    -0.223300
out_prncp_inv                -0.223301
policy_code                        NaN
Name: approval, dtype: float64

In [38]:
x_cols1 = data_cm[(data_cm['approval'] < 1) & (data_cm['approval'] > -0.1)].index.tolist()
x_cols1

['recoveries',
 'collection_recovery_fee',
 'int_rate',
 'total_rec_late_fee',
 'sub_grade',
 'grade',
 'inq_last_6mths',
 'total_rec_int',
 'home_ownership',
 'purpose',
 'term',
 'verification_status',
 'installment',
 'dti',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'pymnt_plan',
 'acc_now_delinq',
 'tot_coll_amt',
 'delinq_2yrs',
 'application_type',
 'collections_12_mths_ex_med',
 'open_acc',
 'total_acc',
 'pub_rec',
 'revol_bal',
 'total_pymnt',
 'total_pymnt_inv',
 'annual_inc',
 'total_rev_hi_lim',
 'tot_cur_bal',
 'initial_list_status',
 'total_rec_prncp']

In [39]:
x1 = data[x_cols1]
y1 = data['approval']
results1 = []
for i in range(10):
    X_train1, X_test1, y_train1, y_test1 = train_test_split(x1, y1,train_size=0.80)
    linreg = LinearRegression()
    model1 = linreg.fit(X_train1,y_train1)
    results1.append(linreg.score(X_test1,y_test1))
round(np.mean(results1),2)*100

31.0

In [40]:
x_cols2 = data_cm[(data_cm.approval > 0.02) & (data_cm.approval < 1.00)].index.tolist()
x_cols2

['recoveries',
 'collection_recovery_fee',
 'int_rate',
 'total_rec_late_fee',
 'sub_grade',
 'grade',
 'inq_last_6mths',
 'total_rec_int',
 'home_ownership',
 'purpose',
 'term',
 'verification_status']

In [41]:
x2 = data[x_cols2]
y2 = data['approval']
results2 = []
for i in range(10):
    X_train2, X_test2, y_train2, y_test2 = train_test_split(x2, y2,train_size=0.80)
    linreg = LinearRegression()
    model2 = linreg.fit(X_train2,y_train2)
    results2.append(linreg.score(X_test2,y_test2))
round(np.mean(results2),2)*100

30.0

In [42]:
custom_cols =['loan_amnt', 'funded_amnt', 'funded_amnt_inv','term', 'int_rate', 'installment', 'grade', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'pymnt_plan', 'purpose','dti','delinq_2yrs','inq_last_6mths', 'open_acc','pub_rec', 'revol_bal', 'revol_util', 'total_acc','initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt','total_pymnt_inv', 'total_rec_prncp', 'total_rec_int','total_rec_late_fee', 'recoveries', 'collection_recovery_fee','collections_12_mths_ex_med', 'policy_code', 'application_type','acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim']
custom_cols

['loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'pymnt_plan',
 'purpose',
 'dti',
 'delinq_2yrs',
 'inq_last_6mths',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'collections_12_mths_ex_med',
 'policy_code',
 'application_type',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'total_rev_hi_lim']

In [43]:
x3 = data[custom_cols]
y3 = data['approval']
results3 = []
for i in range(10):
    X_train3, X_test3, y_train3, y_test3 = train_test_split(x3, y3,train_size=0.80)
    linreg = LinearRegression()
    model3 = linreg.fit(X_train3,y_train3)
    results3.append(linreg.score(X_test3,y_test3))
round(np.mean(results3),2)*100

68.0

In [44]:
y_test_pred = linreg.predict(X_test3)
R_squared = round(r2_score(y_test3, y_test_pred),2)*100
R_squared

68.0

In [45]:
x3 = data[custom_cols]
y3 = data['approval']
results3 = []
for i in range(10):
    X_train3, X_test3, y_train3, y_test3 = train_test_split(x3, y3,train_size=0.80)
    logreg = LogisticRegression()
    model3 = logreg.fit(X_train3,y_train3)
    results3.append(logreg.score(X_test3,y_test3))
round(np.mean(results3),2)*100

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

100.0

In [46]:
y_test_pred2 = logreg.predict(X_test3)
R_squared2 = round(r2_score(y_test3, y_test_pred2),2)*100
R_squared2

90.0

In [47]:
logreg.fit(x3,y3)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
list(y_test_pred2)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [49]:
list(y_test3)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]